name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql-service
      image: mysql:5.7
      env:
        ## Accessing to Github secrets, where you can store your configuration
        MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        MYSQL_DATABASE: snippetbox
      ## map the "external" 33306 port with the "internal" 3306
      ports:
        - 33306:3306
      # Set health checks to wait until mysql database has started (it takes some seconds to start)
      options: >-
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: go build -v ./...
  
    - name: Create MySQL user
      run: mysql -uroot -p${{ secrets.DB_PASSWORD }} < ./ci/scripts/create_user.sql

    - name: Test
      run: go test -v ./...
